/*
===============================================================================
                        REGIONAL ANALYSIS
===============================================================================

Project : Superstore Sales Analysis

Description:
This file evaluates business performance across different geographical
regions and states to identify high-performing markets and locations
requiring strategic improvement.

The objective is to answer the following business questions:

• Which regions generate the highest revenue?
• Which regions generate the highest profit?
• Which states perform above average?
• Which states generate losses despite strong sales?
• Which states require immediate business attention?

These insights help businesses optimize regional strategies, allocate
resources effectively, improve profitability, and identify expansion
opportunities.

===============================================================================
*/

/*
===============================================================================
Business Question:
How does business performance vary across different regions?

Objective:
Compare total sales and profit generated by each region.

Business Value:
Regional performance analysis helps identify strong markets and
regions that require additional business focus or investment.

===============================================================================
*/

SELECT
    Region,
    ROUND(SUM(Sales),2) AS Total_Sales,
    ROUND(SUM(Profit),2) AS Total_Profit
FROM dbo.superstore
GROUP BY Region
ORDER BY Total_Sales DESC;

/*
===============================================================================
Business Question:
How does business performance vary across individual states?

Objective:
Evaluate sales and profitability at the state level.

Business Value:
State-level analysis provides deeper geographical insights and
helps identify high-performing and underperforming markets.

===============================================================================
*/

SELECT
	State_Province AS State,
	ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM dbo.superstore
GROUP BY State_Province
ORDER BY Total_Sales DESC;

/*
===============================================================================
Business Question:
Which states generate above-average profit?

Objective:
Identify states outperforming the company's average profitability.

Business Value:
These states represent successful business markets and may reveal
best practices that can be replicated in other regions.

===============================================================================
*/

SELECT
	State_Province AS State,
	ROUND(SUM(Sales), 2) AS Total_Sales,
	ROUND(SUM(Profit), 2) AS Total_Profit
FROM dbo.superstore
GROUP BY State_Province
HAVING SUM(Profit) > (
	SELECT AVG(Total_Profit)
	FROM (
		SELECT SUM(Profit) AS Total_Profit
		FROM dbo.superstore
		GROUP BY State_Province
	) AS State_Profits
)
ORDER BY Total_Profit DESC;

/*
===============================================================================
Business Question:
Which states generate high sales but negative profit?

Objective:
Identify markets where revenue growth is not translating into
profitability.

Business Value:
These states require investigation into pricing, discounts,
operating costs, and supply chain efficiency.

===============================================================================
*/

SELECT
	State_Province AS State,
	ROUND(SUM(Sales), 2) AS Total_Sales,
	ROUND(SUM(Profit), 2) AS Total_Profit
FROM dbo.superstore
GROUP BY State_Province
HAVING SUM(Profit) < 0
ORDER BY Total_Sales DESC;

/*
===============================================================================
Business Question:
Which states require immediate management attention?

Objective:
Identify states with both high sales volume and negative profitability.

Business Value:
These locations represent the greatest opportunity for improving
overall business profitability through targeted strategic action.

===============================================================================
*/

SELECT
	State_Province,
	ROUND(SUM(Sales), 2) AS TotalSales,
	ROUND(SUM(Profit), 2) AS TotalProfit
FROM dbo.superstore
GROUP BY State_Province
HAVING SUM(Profit) < 0 AND SUM(Sales) > 50000
ORDER BY TotalProfit ASC;

/*
===============================================================================
                     Key Business Takeaways
===============================================================================

• Regional analysis identified the company's strongest and weakest
  geographical markets.

• Several states generate excellent sales while maintaining healthy
  profitability, demonstrating successful business operations.

• Certain high-revenue states continue operating at a loss,
  highlighting opportunities for pricing and cost optimization.

• Above-average performing states can serve as benchmarks
  for improving lower-performing markets.

• These insights support strategic regional planning,
  resource allocation, and long-term business expansion.

===============================================================================
*/
